<?php $sessionUser = new Zend_Session_Namespace('sessionUser'); ?>
    
<?php if ($sessionUser->UserId != null) { ?>
    <div>
    <h3> User Informations : </h3>
    <b>User Id: </b><?php echo $sessionUser->UserId;?><br>
    <b>First Name: </b><?php echo $sessionUser->FName;?><br>
    <b>Last Name: </b><?php echo $sessionUser->LName;?><br>
    <b>Adress: </b><?php echo $sessionUser->Adress;?><br>
    <b>Phone Number: </b><?php echo $sessionUser->PhoneNumber;?><br>
    </div>
<?php } ?>


<?php if ($sessionUser->UserId == null) { ?>
   <div id="Connection">
    <br/>
        <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'login'));
?>">Sign In</a>  
    </div>
<h1> Welcome to the Hospital Application Website. </h1>

<?php } ?>