<?php $sessionUser = new Zend_Session_Namespace('sessionUser'); ?>
    
<?php if ($sessionUser->UserId != null) { ?>
    <div>
    <h3> User Information: </h3>
    <b>User Id: </b><?php echo $sessionUser->UserId;?><br>
    <b>First Name: </b><?php echo $sessionUser->FName;?><br>
    <b>Last Name: </b><?php echo $sessionUser->LName;?><br>
    <b>Adress: </b><?php echo $sessionUser->Adress;?><br>
    <b>Phone Number: </b><?php echo $sessionUser->PhoneNumber;?><br>
    </div>
<?php } ?>


<?php if ($sessionUser->UserId == null) { ?>
   <div id="Connection">
    <br/>
        <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'login'));
?>">Sign In</a>  
    </div>
<h1> Welcome to the Hospital Application Website. </h1>

<p>This is a project for CPSC 471, that acts as a web applicaiton for a potential hospital or medical clinic.
	There are three types of users that use this application, a secretary, a doctor, and a patient.</p>
	
<p>A secretary is the administrator of the web application, they can add an edit users or patients, manage appointments,
	 view doctors schedules, modify patients files, send alerts to other secretaries or doctors, and manage patients meal plans</p>
<p>A doctor can view his or her schedule, add notes to a patients file, and send alerts</p>
<p> A patient can access the application, only if they are a long term patient, and can rent movies or manage their meal plan</p>

<?php } ?>