<?php $sessionUser = new Zend_Session_Namespace('sessionUser'); ?>
<h2>Your Information:</h2>
    <b>User Id: </b><?php echo $sessionUser->UserId;?><br>
    <b>First Name: </b><?php echo $sessionUser->FName;?><br>
    <b>Last Name: </b><?php echo $sessionUser->LName;?><br>
    <b>Adress: </b><?php echo $sessionUser->Adress;?><br>
    <b>Phone Number: </b><?php echo $sessionUser->PhoneNumber;?><br>
    <b>Patient Id: </b><?php echo $sessionUser->PatientId;?><br>
    <b>Prefered Doctor: </b> Dr <?php echo $this->PreferedDoctor->LName;?> <?php echo $this->PreferedDoctor->FName;?><br>

<h2> Your Meal Plan :</h2>
<table>
    <tr>
        <th>Type</th>
        <th>Sunday</th>
        <th>Monday</th>
        <th>Tuesday</th>
        <th>Wednesday</th>
        <th>Thursday</th>
        <th>Friday</th>
        <th>Saturday</th>
    </tr>
        <tr>
           <td><?php echo $this->escape($this->userMealPlan->Type); ?></td>
           <td><?php echo $this->escape($this->userMealPlan->Sunday); ?></td>
           <td><?php echo $this->escape($this->userMealPlan->Monday); ?></td>
           <td><?php echo $this->escape($this->userMealPlan->Tuesday); ?></td>
           <td><?php echo $this->escape($this->userMealPlan->Wednesday); ?></td>
           <td><?php echo $this->escape($this->userMealPlan->Thursday); ?></td>
           <td><?php echo $this->escape($this->userMealPlan->Friday); ?></td>
           <td><?php echo $this->escape($this->userMealPlan->Saturday); ?></td>        
        </tr>
</table>
    
<h2>Your Rents :</h2>
<table>
    <tr>
        <th>Name</th>
        <th>To</th>
        <th>Until</th>
    </tr>
    <?php foreach ($this->userRents as $r) : ?>
        <tr>
           <td><?php echo $this->escape($r->Name); ?></td>
           <td><?php echo $this->escape($r->BeginDate); ?></td>  
           <td><?php echo $this->escape($r->EndDate); ?></td>  
        </tr>
    <?php endforeach; ?>
</table>

