<?php $sessionUser = new Zend_Session_Namespace('sessionUser');
if($sessionUser->successMessage != "")
{
	echo "<div class='successMessage' style='display:block'>" . $sessionUser->successMessage . "</div>";
}
$sessionUser->successMessage = "";

 ?>

<h2> <a href="<?php echo $this->url(array('controller' => 'appointment',
                           'action' => 'patientappointment')); ?>">Add</a>
or <a href="<?php echo $this->url(array('controller' => 'appointment',
                           'action' => 'searchappointment')); ?>">Edit</a>
an Appointment?                        
</h2>