<?php $sessionUser = new Zend_Session_Namespace('sessionUser'); ?>
<h2>First</h2>
Search a Patient:
<?php
    echo $this->form ;
?>

<table>
    <tr>
    	<th>Id</th>
        <th>Name</th>
        <th>Type</th>
        <th>Schedule?</th>

    </tr>
    <?php foreach ($this->allpatients as $a) : ?>
        
        <tr>
           <td><?php echo $this->escape($a->PatientId); ?> </td>  
           <td><?php echo $this->escape($a->LName); ?> <?php echo $this->escape($a->FName);?> </td>
           <td><?php echo $this->escape($a->PatientType); ?></td>
           <td><a style="color:black;" href="<?php echo $this->url(array('controller' => 'appointment',
                           'action' => 'doctorappointment', 'patientid' => $a->PatientId)); ?>">Schedule</a></td>

        </tr>                                        
    <?php  endforeach; ?>
</table>