<?php $sessionUser = new Zend_Session_Namespace('sessionUser'); ?>
<h2>Select a Room:</h2>
Search by floor:
<?php

    echo $this->form ;
	$pid = $this->pid;
	$did = $this->did;
	$hour= $this->hour;
?>

<table>
    <tr>
    	<th>Id</th>
        <th>Number</th>
        <th>Floor</th>
        <th>Type</th>
        <th>Choose?</th>

    </tr>
    <?php foreach ($this->allrooms as $a) : ?>
    	
        
        <tr>
           <td><?php echo $this->escape($a->RoomId); ?> </td>  
           <td><?php echo $this->escape($a->Number); ?> </td>
           <td><?php echo $this->escape($a->Floor); ?></td>
           <td><?php echo $this->escape($a->RoomType); ?></td>
           <td><a style="color:black;" href="<?php echo $this->url(array('controller' => 'appointment',
                           'action' => 'confirmappointment', 'roomid' => $a->RoomId)); ?>">Choose</a></td>
         
        </tr>                                        
    <?php  
    endforeach; ?>
</table>