
    <div>
    <h3> Appointment Informations :</h3>
    <b>Schedule Id: </b><?php echo $this->app->Sid;?><br>
    <b>Doctor: </b><?php echo $this->app->LName;?> <?php echo $this->app->FName;?><br>
    <b>Patient: </b><?php echo $this->app->PLName;?> <?php echo $this->app->PFName;?><br>
    <b>Room: </b><br>
    Number: <?php echo $this->app->Number;?><br>
    Floor: <?php echo $this->app->Floor;?><br>
    Section: <?php echo $this->app->Section;?><br>
    Type: <?php echo $this->app->RoomType;?><br>
    </div>
