
<?php
	if ($this->errorMessage != "")
		echo "<div class='errorMessage' style='display:block'>" . $this->errorMessage . "</div>";
	$this->errorMessage = "";
	if ($this->patientid == NULL)
		$patientid = "0";
	else
		$patientid = $this->$patientid;
		
	if ($this->doctorid == NULL)
		$doctorid = "0";
	else
		$doctorid = $this->$doctorid;
	
	if ($this->roomid == NULL)
		$roomid = "0";
	else
		$roomid = $this->$roomid;
		
?>

<h2>Add An Appointment:</h2>
Enter the Appointment Information here:


<a style="color:black;" href="<?php echo $this->url(array('controller' => 'secretary',
                           'action' => 'patientappointment', 'patientid' => $patientid, 'doctorid' => $doctorid, 'roomid' => $roomid)); ?> ">Find A Patient</a>
<a style="color:black;" href="<?php echo $this->url(array('controller' => 'secretary',
   'action' => 'doctorappointment', 'patientid' => $patientid, 'doctorid' => $doctorid, 'roomid' => $roomid)); ?>">Find A Doctor</a>
<a style="color:black;" href="<?php echo $this->url(array('controller' => 'secretary',
   'action' => 'roomappointment', 'patientid' => $patientid, 'doctorid' => $doctorid, 'roomid' => $roomid)); ?>">Find A Room</a>
<?php	
    echo $this->form ;
?>