<h3> Doctors : </h3>
<table>
    <tr>
    	<th>Id</th>
        <th>Name</th>
        <th>&nbsp;</th>

    </tr>
    <?php foreach ($this->doctors as $a) :  ?>   
        <tr>
           <td><?php echo $this->escape($a->UserId); ?> </td>  
           <td><?php echo $this->escape($a->LName); ?> <?php echo $this->escape($a->FName);?> </td>
           <td><a style="color:black;" href="<?php echo $this->url(array('controller' => 'schedule',
                           'action' => 'viewschedule', 'doctorid' => $a->UserId)); ?>">View Schedule</a></td>
         
        </tr>                                        
    <?php endforeach; ?>
</table>
