<?php $sessionUser = new Zend_Session_Namespace('sessionUser'); ?>
<h2>Search For A Patient:</h2>
Search a Patient:
<?php
    echo $this->form ;
		
	if ($this->doctorid == NULL)
		$doctorid = "0";
	else
		$doctorid = $this->$doctorid;
	
	if ($this->patientid == NULL)
		$patientid = "0";
	else
		$patientid = $this->$patientid;
	
	
?>

<table>
    <tr>
    	<th>Id</th>
        <th>Floor</th>
        <th>Number</th>
        <th>Section</th>
        <th>Type</th>
        <th>LongTerm?</th>
        <th>Available Beds</th>
        <th>Schedule?</th>

    </tr>
    <?php foreach ($this->allrooms as $a) :
           	if($a->NumberOfBed == $this)
	?>
        
        <tr>
           <td><?php echo $this->escape($a->RoomId); ?> </td>  
           <td><?php echo $this->escape($a->Floor); ?> </td>
           <td><?php echo $this->escape($a->Number); ?></td>
           <td><?php echo $this->escape($a->Section); ?></td>
           <td><?php echo $this->escape($a->RoomType); ?></td>
           <td><?php 
           if($a->NumberOfBed == NULL)
		   		echo "No";
		   else
           		echo "Yes"; 
       
           ?></td>
           <td><?php echo $this->escape($this->available[$a->RoomId]); ?></td>
           <td>
           	<a style="color:black;" href="<?php echo $this->url(array('controller' => 'secretary',
                           'action' => 'addappointment', 'patientid' => $patientid, 'doctorid' => $doctorid, 'roomid' => $a->RoomId)); ?>">Schedule</a>
          </td>

        </tr>                                        
    <?php  endforeach; ?>
</table>