<?php $sessionUser = new Zend_Session_Namespace('sessionUser'); ?>
<h2>Which Doctor Would You Like To Edit :</h2>
Search a user:
<?php
    echo $this->form ;
?>

<table>
    <tr>
    	<th>Id</th>
        <th>Name</th>
        <th>Type</th>
        <th>Edit?</th>

    </tr>
    <?php foreach ($this->allusers as $a) : 
    	if (strcmp(strtoupper($a->UserType),"DOCTOR") == 0){?>
        
        <tr>
           <td><?php echo $this->escape($a->UserId); ?> </td>  
           <td><?php echo $this->escape($a->LName); ?> <?php echo $this->escape($a->FName);?> </td>
           <td><?php echo $this->escape($a->UserType); ?></td>
           <td><a style="color:black;" href="<?php echo $this->url(array('controller' => 'secretary',
                           'action' => 'editdoctor', 'userid' => $a->UserId)); ?>">Edit</a></td>
         
        </tr>                                        
    <?php  }
    endforeach; ?>
</table>
