<?php $sessionUser = new Zend_Session_Namespace('sessionUser'); ?>
    
    <div>
    <h2>Your Informations : </h2>
    <b>User Id: </b><?php echo $sessionUser->UserId;?><br>
    <b>First Name: </b><?php echo $sessionUser->FName;?><br>
    <b>Last Name: </b><?php echo $sessionUser->LName;?><br>
    <b>Adress: </b><?php echo $sessionUser->Adress;?><br>
    <b>Phone Number: </b><?php echo $sessionUser->PhoneNumber;?><br>
    <b>Section: </b><?php echo $this->doctor->Section;?><br>
    <b>Specialities: </b> <?php foreach ($this->specialities as $s) : ?> 
                                <?php echo $s->Speciality.', '?>
                          <?php endforeach; ?>
    
    <h2>Your Next Appointment : </h2>
    <?php if ( $this->next != null) { ?>
    <?php echo $this->next->DateS;?> between <?php echo $this->next->BeginTime;?> and <?php echo $this->next->EndTime;?> <a href="<?php echo $this->url(array('controller' => 'schedule',
                           'action' => 'viewappointment', 'Sid' => $this->next->Sid)); ?>">More Infos</a>
    <?php } else { ?>
        <?php echo "Nothing";?>
    <?php } ?>
    <h2>Your Last Alerts : </h2>
    <table>
    <tr>
        <th>From </th>
        <th>Date</th>
        <th>Description</th>
        <th>&nbsp</th>
    </tr>
    <?php foreach ($this->lastalerts as $a) : ?>
        <tr>
           <td><?php echo $this->escape($a->LName); ?> <?php echo $this->escape($a->FName);?> (<?php echo $this->escape($a->UserType);?>)</td>
           <td><?php echo $this->escape($a->DateA); ?> (<?php echo $this->escape($a->TimeA); ?>)</td>  
           <td><?php echo $this->escape($a->Description); ?></td>
           <td><a href="<?php echo $this->url(array('controller' => 'alert',
                           'action' => 'sendalert', 'receiverid' => $a->SenderId, 'receivername' => $a->LName.' '.$a->FName)); ?>">Reply</a></td>
        </tr>                                        
    <?php endforeach; ?>
</table>
    
    
    </div>
